### ISSUE TITLE
welle.io uses rtl_tcp_andro-

### ISSUE THREAD

**Issue by AlbrechtL** [martinmarinov/rtl_tcp_andro-#14]
[welle.io](https://www.welle.io) (an open source DAB/DAB+ SDR receiver software) uses your great driver!

Google Play: https://play.google.com/store/apps/details?id=io.welle.welle
Website: https://www.welle.io
Source: https://github.com/AlbrechtL/welle.io

I would be very happy if you add welle.io to the supported app list.

**Comment by martinmarinov** [comment]
Done :) Good luck with the project!
