### ISSUE TITLE
ADSB Flight Tracker.

### ISSUE THREAD

**Issue by Enthusiastic-Coder** [martinmarinov/rtl_tcp_andro-#18]
Hi Sir

I have recently incorporated the use of your RTL SDR driver in my app see here.

https://play.google.com/store/apps/details?id=com.enthusiasticcoder.adsbflightmonitor&hl=en

I was hoping if you could added it to your list of compatible apps?

Thanks

**Comment by martinmarinov** [comment]
Thanks for your pull request

**Comment by Enthusiastic-Coder** [comment]
No worries!
