### ISSUE TITLE
libusb_andro in it's own repo

### ISSUE THREAD

**Issue by kellycampbell** [martinmarinov/rtl_tcp_andro-#2]
FYI, I made a fork of libusb and ported your patch to it to make it more easily accessible:
https://github.com/BuLogics/libusb/commits/android_usbfd

I also have a libusb-compat-0.1 which supports the calls for android with file descriptors:
https://github.com/BuLogics/libusb-compat-0.1/tree/android_usbfd

**Comment by martinmarinov** [comment]
Thanks for letting me know.

The current solution was not working on Android N. I used https://github.com/kuldeepdhaka/libusb and modified it to make it work correctly on Android N. See latest commit for info.
