### ISSUE TITLE
device_filter.xml uses hex values

### ISSUE THREAD

**Issue by bkhall** [martinmarinov/rtl_tcp_andro-#3]
The product-id and vendor-id values are supposed to be in decimal format, not hex.

I see that you convert them from hex to decimal internally however, so the app is working.

Still, this file should be portable to other projects which are expecting the standard format.

**Comment by martinmarinov** [comment]
Hey,

The values were in the xml file were in decimal. However, with the latest commit they are back in hex, the same format that the rtlsdr library uses

https://github.com/martinmarinov/rtl_tcp_andro-/commit/850450f3de763e9859fcc81e78216d0c4a005cfd
