### ISSUE TITLE
Nexus 7 Android 5.02 not seeing device

### ISSUE THREAD

**Issue by GeoNomad** [martinmarinov/rtl_tcp_andro-#4]
Does the driver support Android 5.02?

It reports device not found. The device works with a PC and the OTG cable works with dongles and hard drives.

I also have a Nexus 5, but it is also running 5.02. My old Samsung is probably not powerful enough...

Peter

**Comment by Yurisu** [comment]
I aoso have this problem.when my samsung note3 updated to android 5.0.

error starting! reason: root_required

**Comment by martinmarinov** [comment]
The driver does support Android 5. It might be an OTG cable issues, I've seen problems with cables working on some devices but not on others.
