### ISSUE TITLE
A break bug:java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by ywm0822** [martinmarinov/rtl_tcp_andro-#5]
Hello,
we recently tested your app rtl_tcp by an automated Android GUI testing tool developed by our team, and we found a bug that the app will break when we click.Here is the trace.
1. click the "Enable advanced mode" button;
2.choose the "Force root" checkbox;
3.click the "Start stream" button, and the app will break immediately.
Here is the log we dumped:
E/AndroidRuntime(16257): FATAL EXCEPTION: main
E/AndroidRuntime(16257): Process: a3e.process, PID: 16257
E/AndroidRuntime(16257): java.lang.UnsatisfiedLinkError: Couldn't load RtlTcp from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/umd.troyd-1.apk", zip file "/data/app/marto.rtl_tcp_andro-1.apk"],nativeLibraryDirectories=[/data/app-lib/umd.troyd-1, /data/app-lib/marto.rtl_tcp_andro-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/AndroidRuntime(16257): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime(16257): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(16257): 	at marto.rtl_tcp_andro.core.RtlTcp.<clinit>(RtlTcp.java:45)
E/AndroidRuntime(16257): 	at marto.rtl_tcp_andro.tools.BinaryRunnerService.start(BinaryRunnerService.java:89)
E/AndroidRuntime(16257): 	at marto.rtl_tcp_andro.DeviceOpenActivity$1.onServiceConnected(DeviceOpenActivity.java:77)
E/AndroidRuntime(16257): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1103)
E/AndroidRuntime(16257): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1120)
E/AndroidRuntime(16257): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(16257): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16257): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(16257): 	at android.app.ActivityThread.main(ActivityThread.java:5135)
E/AndroidRuntime(16257): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16257): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16257): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime(16257): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime(16257): 	at dalvik.system.NativeStart.main(Native Method)
Here is the suspicious code snippet:
![screen shot 2016-04-11 at 3 47 24 pm](https://cloud.githubusercontent.com/assets/14055020/14420176/0f771d0e-fffd-11e5-8db6-8a4521955481.png)
Could you please take a look and confirm this bug? Thanks a lot!
ywm0822 AT gmail DOT com

**Comment by tingsu** [comment]
Hello Martin, Can you help us confirm this bug?

**Comment by martinmarinov** [comment]
Hey,

Can you confirm the emulator you are using is among the supported
architectures?

This message looks as if the native library does not exists/was not
compiled/is not supported on the current architecture.

Martin

**Comment by tingsu** [comment]
Thanks so much for your reply, Martin. Can you point out which architectures are supported? We are using real Android phones shipped with KitKat (Android SDK 4.4.4 - API level 20), CPU Cortex-A53.

Yes, I agree with you that the bug is triggered because the native library does not exists on the phone. So  maybe a new version should catch this possible exception and give a warning message. That would be better.

Ting

**Comment by martinmarinov** [comment]
This should fix the problem

https://github.com/martinmarinov/rtl_tcp_andro-/commit/57a378c0426a6ff9318ee9c5e607b17d8fc842ad

Feel free to re-open if the fix doesn't work.
